### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by ingbeck** [neuefische/hh-java-24-1-team-3#12]
**As a User** 
**I need** a possibility to search for specific details
**to be able to** find the restaurants that fit my needs.

## Description
Implement a feature that allows users to search for a specific detail and lists all restaurants that have those details.

## Acceptance Criteria

- [ ] The header should contain a title, a logo and a searchbar
- [ ] The searchbar should accept text and filter the full list in real time according to the searchbars text
- [ ] Ensure that the filtered restaurants appear in the list of restaurants.

## Tasks

(for developers team)

Frontend:
- [ ] create a 'Header' with a title and logo 
- [ ] add a 'SearchBarComponent' to the 'Header'
- [ ] add functionality to filter and display the full list of restaurants
- [ ] add some styling
