### ISSUE TITLE
Additional restaurant information

### ISSUE THREAD

**Issue by JanaS87** [neuefische/hh-java-24-1-team-3#16]
**As a User** 
**I need** additional information about the restaurants location and its cuisine
**to be able to** see which kind of restaurant is near by.

## Description
Implement a feature that allows users to see the restaurants address and the offered cuisine

## Acceptance Criteria

- [ ] Show the address (street, number) and the cuisine (e.g. thai, high class, Italian, ...) an the restaurants detail page
- [ ] When creating a new restaurant the address and the cuisine should be mandatory

## Tasks

(for developers team)

- [x] extend the model for Restaurant with  a field for "cuisine" and a field of an new model "RestaurantAdress" which
has the fields "address" and "number"
- [x] update all methods und tests where the model Restaurant is used
- [x] extend the type Restaurant to receive the according data from the backend
- [x] update the "RestaurantDetail" component to display the address and the cuisine
- [x] update the "AddRestaurant" component to create a restaurant with an address and an offered cuisine
- [ ] add some styling
