### ISSUE TITLE
Edit (PUT) restaurant

### ISSUE THREAD

**Issue by ingbeck** [neuefische/hh-java-24-1-team-3#18]
**As a User**
**I need** to edit the details of a restaurant in my library
**to be able to** update information for a restaurant

#### Description
Implement a feature that allows users to edit the details of a restaurant. Users should be able to modify the title and the city, not the id.

#### Acceptance Criteria

- [x] A "Edit"-Button is displayed on the details-page for each-restaurant.
- [x] When the "Edit" button for a restaurant is clicked, the user gets redirected to "/restaurants/:id/edit
- [x] On the Edit-Page an edit form for that restaurant should appear.
- [x] When submitting the form, then the restaurant information should be updated in the backend and the user should be redirected to the details page.
- [x] Create an PUT Endpoint "/api/restaurants/{id} to update the restaurant.

#### Tasks

- [x] Add an "Edit" button for each restaurant in the UI.
- [x] Implement an edit form to modify restaurant details.
- [x] Create a PUT request to update restaurant details on the backend.
- [ ] Display updated information in the frontend after saving changes.
- [x] Implement Unit and Integration Test.
