### ISSUE TITLE
Kartenansicht

### ISSUE THREAD

**Issue by JanaS87** [neuefische/hh-java-24-1-team-3#25]
As a user, I want a little map besides the restaurant informations,
so I can see where this restaurant is located at.

## Description

Implement a map for the restaurants location

## Acceptance Criteria

- [x] every restaurant is still clickable and leads to the Detail Card
- [x] on the Detail Card, every information is clearly readable and understandable
- [x] on the right, there is a map which shows the restaurants location

## Tasks

- [x] install Leaflet (rpm)
- [x] include Leaflet CSS file in index.html
- [x] include Leaflet JS file after the CSS file
- [x] place a div with the needed id="map"
- [x] implement the needed code for the map
