### ISSUE TITLE
GET all restaurants

### ISSUE THREAD

**Issue by emea94** [neuefische/hh-java-24-1-team-3#5]
**As a User** 
**I need** to view a list of all my restaurants
**to be able to** have a comprehensive overview of my entire list.

## Description
Implement a feature that allows users to retrieve and view a list of all their restaurants from the backend.

## Acceptance Criteria

- [x] Create a GET "/api/restaurants" endpoint to fetch all restaurants from the backend.
- [x] Display the list of all restaurants on the starting page of the frontend.

## Tasks

(for developers team)

- [x] Create a Model with "Id, title and city"
- [x] Create a "View All restaurants" component in the UI.
- [x] Implement a GET request to retrieve all restaurants from the backend.
- [x] Update the frontend to display the list of restaurants.
- [x] Implement Unit and Integration Test.
- [x] add some styling
